import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import Navbar from '../../components/Navbar';

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="prose prose-lg max-w-none"
        >
          <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-gray-600 mb-8">Last updated: February 05, 2025</p>

          <div className="space-y-8">
            {/* Introduction */}
            <section>
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </section>

            {/* Interpretation and Definitions */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Interpretation and Definitions</h2>
              
              <h3 className="text-xl font-semibold mb-3">Interpretation</h3>
              <p>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="text-xl font-semibold mb-3 mt-6">Definitions</h3>
              <p>For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li>We operate under the brand name Advizy ('we,' 'us,' 'our') as an independent service provider. Advizy is currently in the process of incorporation. Until formal incorporation, all services are provided in an individual capacity, and no corporate liability is assumed.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country</strong> refers to India. Advizy currently operates from Maharashtra.</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website and any related services, including mobile applications, offered by us.</li>
                <li><strong>Service Provider</strong> means any third-party individual or entity that assists in operating Advizy's platform, including hosting, analytics, and customer support services.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>Website</strong> refers to the Advizy platform, accessible at http://www.advizy.in</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </section>

            {/* Collecting and Using Personal Data */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Collecting and Using Your Personal Data</h2>
              
              <h3 className="text-xl font-semibold mb-3">Types of Data Collected</h3>
              
              <h4 className="text-lg font-semibold mb-2">Personal Data:</h4>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
              </ul>

              <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data:</h4>
              <p>Usage Data is collected automatically when using the Service.</p>
              <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

              <h4 className="text-lg font-semibold mt-4 mb-2">Google API</h4>
              <p>Our access and use of Google API data comply with the Google API Services User Data Policy, including the Limited Use requirements.</p>
              <p><a href="https://developers.google.com/terms/api-services-user-data-policy" className="text-primary hover:underline">https://developers.google.com/terms/api-services-user-data-policy</a></p>

              <h4 className="text-lg font-semibold mt-4 mb-2">Payment Data</h4>
              <p>We may collect data necessary to process your payment if you choose to make purchases, such as your payment instrument number, and the security code associated with your payment instrument. All payment data may handled and stored by Razorpay services. You may find their privacy notice link(s) here:</p>
              <p><a href="https://razorpay.com/privacy/" className="text-primary hover:underline">https://razorpay.com/privacy/</a></p>
            </section>

            {/* Tracking Technologies and Cookies */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Tracking Technologies and Cookies</h2>
              <p>We may use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>

              <h4 className="text-lg font-semibold mt-4 mb-2">Cookies or Browser Cookies</h4>
              <p>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>

              <h4 className="text-lg font-semibold mt-4 mb-2">Google Analytics</h4>
              <p>We use Google Analytics to analyze website traffic and improve user experience. You can opt out of Google Analytics tracking by using the official Google opt-out tool: <a href="https://tools.google.com/dlpage/gaoptout" className="text-primary hover:underline">https://tools.google.com/dlpage/gaoptout</a></p>

              <h4 className="text-lg font-semibold mt-4 mb-2">Web Beacons</h4>
              <p>Our Service and emails may contain web beacons that help us track user interactions, such as page visits and email opens. These beacons assist in improving website analytics, monitoring service performance, and ensuring system security.</p>

              <h4 className="text-lg font-semibold mt-4 mb-2">Types of Cookies We Use</h4>
              <ul className="list-disc pl-6 space-y-4">
                <li>
                  <strong>Necessary / Essential Cookies:</strong><br />
                  Type: Session Cookies<br />
                  Administered by: Us<br />
                  Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.
                </li>
                <li>
                  <strong>Functionality Cookies:</strong><br />
                  Type: Persistent Cookies<br />
                  Administered by: Us<br />
                  Purpose: These Cookies allow us to remember choices You make when You use the Website,such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.

                  For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
                  <p><Link to="/cookie-policy" className="text-primary hover:underline">Cookie Policy</Link></p>
                </li>
              </ul>
            </section>

            {/* Use of Personal Data */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Use of Your Personal Data</h2>
              <p>We may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To provide and maintain our Service</li>
                <li>To manage Your Account</li>
                <li>For the performance of a contract</li>
                <li>To contact You</li>
                <li>To manage Your requests</li>
                <li>For business transfers</li>
                <li>For other purposes such as data analysis and service improvement</li>
              </ul>
            </section>

            {/* Data Sharing */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Sharing of Your Personal Data</h2>
              <p>We may share Your personal information in the following situations:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>With Service Providers</li>
                <li>For business transfers</li>
                <li>With Affiliates</li>
                <li>With business partners</li>
                <li>With other users</li>
                <li>With Your consent</li>
              </ul>
            </section>

            {/* Data Retention */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Retention of Your Personal Data</h2>
              <p>We will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
            </section>

            {/* Data Transfer */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Transfer of Your Personal Data</h2>
              <p>Your Personal Data may be processed and stored in jurisdictions outside your country of residence. By using our Service, you consent to such transfers. We implement appropriate safeguards to protect your data during any transfers.</p>
            </section>

            {/* Delete Your Data */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Delete Your Personal Data</h2>
              <p>You may request deletion of your Personal Data by contacting us at support@advizy.in. Some data may be retained for legal compliance, fraud prevention, or dispute resolution.</p>
            </section>

            {/* Security */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Security of Your Personal Data</h2>
              <p>While we implement commercially reasonable security measures, no method of transmission over the Internet is 100% secure. We cannot guarantee absolute security of your Personal Data.</p>
            </section>

            {/* Children's Privacy */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Children's Privacy</h2>
              <p>Our Service is not intended for individuals under 18. We do not knowingly collect data from minors. Contact us if you believe we have collected data from a minor.</p>
            </section>

            {/* Links to Other Websites */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Links to Other Websites</h2>
              <p>Our Service may contain links to third-party websites not controlled by us. We are not responsible for their privacy practices. Review their privacy policies before sharing personal data.</p>
            </section>

            {/* Changes to Privacy Policy */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Changes to this Privacy Policy</h2>
              <p>We may update this Privacy Policy periodically. Changes are effective when posted on this page. We will notify you of any material changes.</p>
            </section>

            {/* Contact Information */}
            <section>
              <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
              <p>If you have questions about this Privacy Policy, contact us:</p>
              <p>By visiting: <a href="http://www.advizy.in/contact" className="text-primary hover:underline">http://www.advizy.in/contact</a></p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;